# Generated by Django 2.0.7 on 2018-09-03 22:28

import collectionsapp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='Product')),
                ('flavor', models.CharField(blank=True, max_length=100, verbose_name='Flavor')),
                ('color', models.IntegerField(blank=True, default=None, null=True, verbose_name='Color')),
                ('beverage_type', models.IntegerField(choices=[(0, ''), (1, 'Soda'), (2, 'Beer'), (3, 'Water'), (4, 'Milk'), (5, 'Kombucha')], default=0, verbose_name='Beverage Type')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Text')),
                ('underside', models.CharField(blank=True, max_length=50, verbose_name='Underside')),
                ('date_acquired', models.DateField(default=datetime.date.today, verbose_name='Date Acquired')),
                ('method_acquired', models.IntegerField(choices=[(0, ''), (1, 'Donated'), (2, 'Purchased'), (3, 'Traded'), (4, 'Found')], default=0, verbose_name='Method Acquired')),
                ('spares_available', models.BooleanField(default=False, verbose_name='Spares Available')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('number_in_collection', models.IntegerField(verbose_name='Number in collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BottleCapIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecapicon_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecapicon_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectiontype_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectiontype_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.CollectionType'),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collection_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='modified_by',
            field=models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collection_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collection_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.Collection', verbose_name='Collection ID'),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='created_by',
            field=models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='icons',
            field=models.ManyToManyField(to='collectionsapp.BottleCapIcon', verbose_name='Icons'),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='modified_by',
            field=models.ForeignKey(default=collectionsapp.models.get_unknown_user, on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecap_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
