# Generated by Django 2.0.7 on 2018-09-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontype',
            name='render_page_name',
            field=models.CharField(default='bottle_cap_item/', max_length=100),
            preserve_default=False,
        ),
    ]
