# Generated by Django 2.0.7 on 2018-08-24 18:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCapIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='beverage_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Soda'), (2, 'Beer'), (3, 'Water'), (4, 'Milk'), (5, 'Kombucha')], default=0),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='date_acquired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='method_acquired',
            field=models.IntegerField(choices=[(0, ''), (1, 'Donated'), (2, 'Purchased'), (3, 'Traded')], default=0),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='spares_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='underside',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectiontype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiontype',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bottlecapicon',
            name='bottle_cap',
            field=models.ManyToManyField(to='collectionsapp.BottleCap'),
        ),
    ]
