# Generated by Django 2.0.7 on 2018-08-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0002_auto_20180824_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecap',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='bottlecap',
            name='variety',
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='flavor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='product',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='method_acquired',
            field=models.IntegerField(choices=[(0, ''), (1, 'Donated'), (2, 'Purchased'), (3, 'Traded'), (4, 'Found')], default=0),
        ),
    ]
