# Generated by Django 2.2 on 2019-04-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0002_auto_20190421_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.CollectionType', verbose_name='Collection Type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsapp_collection_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='CollectionFieldset',
        ),
    ]
