# Generated by Django 2.0.7 on 2018-09-05 03:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('collectionsapp', '0002_collectiontype_render_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecapicon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bottlecapicon',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='bottlecap',
            name='icons',
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='BottleCapIcon',
        ),
    ]
