# Generated by Django 2.2 on 2019-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0002_auto_20190511_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beveragetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Beverage type'),
        ),
        migrations.AlterField(
            model_name='methodacquired',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Method acquired'),
        ),
    ]
