# Generated by Django 2.2 on 2019-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0003_auto_20190426_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
