# Generated by Django 2.0.7 on 2018-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0003_auto_20180825_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecapicon',
            name='bottle_cap',
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='icon',
            field=models.ManyToManyField(to='collectionsapp.BottleCapIcon'),
        ),
    ]
