# Generated by Django 2.0.7 on 2018-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0003_auto_20180904_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
