# Generated by Django 2.0.7 on 2018-08-26 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0004_auto_20180825_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecap',
            name='icon',
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='color',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='icons',
            field=models.ManyToManyField(to='collectionsapp.BottleCapIcon', verbose_name='Icons'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='beverage_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Soda'), (2, 'Beer'), (3, 'Water'), (4, 'Milk'), (5, 'Kombucha')], default=0, verbose_name='Beverage Type'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.Collection', verbose_name='Collection ID'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='date_acquired',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Acquired'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='flavor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Flavor'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='method_acquired',
            field=models.IntegerField(choices=[(0, ''), (1, 'Donated'), (2, 'Purchased'), (3, 'Traded'), (4, 'Found')], default=0, verbose_name='Method Acquired'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='product',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='spares_available',
            field=models.BooleanField(default=False, verbose_name='Spares Available'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='underside',
            field=models.CharField(blank=True, max_length=50, verbose_name='Underside'),
        ),
    ]
