# Generated by Django 2.0.7 on 2018-09-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0004_auto_20180904_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecap',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='bottlecap',
            name='spares_available',
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='available_for_trade',
            field=models.BooleanField(default=False, verbose_name='Available For Trade'),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='variety',
            field=models.CharField(blank=True, max_length=100, verbose_name='variety'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='method_acquired',
            field=models.IntegerField(choices=[(0, ''), (1, 'Donated'), (2, 'Purchased'), (3, 'Traded'), (4, 'Found'), (5, 'Created')], default=0, verbose_name='Method Acquired'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
