# Generated by Django 2.2 on 2019-04-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0004_auto_20190429_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemimage',
            name='order_in_collection',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
