# Generated by Django 2.2 on 2019-05-03 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectionsapp', '0005_auto_20190429_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsapp_beveragetype_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsapp_beveragetype_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='beverage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.BeverageType', verbose_name='Beverage Type'),
        ),
    ]
