# Generated by Django 2.0.7 on 2018-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0005_auto_20180905_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiontype',
            old_name='render_page_name',
            new_name='view_name',
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='variety',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variety'),
        ),
    ]
