# Generated by Django 2.2.3 on 2019-07-11 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectionsapp', '0006_auto_20190522_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItemImageThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('image', models.ImageField(upload_to='thumbnails/', verbose_name='Image')),
                ('order_in_collection', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('collection_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.BottleCap', verbose_name='Collection Item')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsapp_collectionitemimagethumbnail_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsapp_collectionitemimagethumbnail_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
