# Generated by Django 2.2.3 on 2019-08-05 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0007_collectionitemimagethumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecap',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='beveragetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_beveragetype_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='beveragetype',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_beveragetype_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionsapp.Collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecap_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_bottlecap_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collection_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collection_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='collectionitemimage',
            name='collection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionsapp.BottleCap', verbose_name='Collection Item'),
        ),
        migrations.AlterField(
            model_name='collectionitemimage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectionitemimage_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='collectionitemimage',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectionitemimage_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='collectionitemimagethumbnail',
            name='collection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionsapp.BottleCap', verbose_name='Collection Item'),
        ),
        migrations.AlterField(
            model_name='collectionitemimagethumbnail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectionitemimagethumbnail_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='collectionitemimagethumbnail',
            name='image',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='ImageThumbnail'),
        ),
        migrations.AlterField(
            model_name='collectionitemimagethumbnail',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectionitemimagethumbnail_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectiontype_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_collectiontype_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='methodacquired',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_methodacquired_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='methodacquired',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectionsapp_methodacquired_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
