# Generated by Django 2.2.3 on 2019-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0008_auto_20190804_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecap',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='bottlecap',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='ImageThumbnail'),
        ),
    ]
