# Generated by Django 2.2.3 on 2019-08-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0009_auto_20190823_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecap',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bottlecap',
            name='image_thumbnail',
        ),
    ]
