# Generated by Django 2.2.3 on 2019-08-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0010_auto_20190823_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlecap',
            name='beverage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.BeverageType', verbose_name='Beverage Type'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='method_acquired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collectionsapp.MethodAcquired', verbose_name='Method Acquired'),
        ),
    ]
