# Generated by Django 2.2.4 on 2020-05-10 01:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectionsapp', '0013_auto_20190824_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.date.today, verbose_name='Date Acquired')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Text')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
