# Generated by Django 2.2.4 on 2020-05-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0014_searchaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchaction',
            name='timestamp',
            field=models.DateField(verbose_name='Timestamp'),
        ),
    ]
