# Generated by Django 3.0.6 on 2020-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0016_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchaction',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
