# Generated by Django 3.0.6 on 2020-05-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0017_auto_20200510_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beveragetype',
            options={'ordering': ['name']},
        ),
    ]
