# Generated by Django 3.0.6 on 2020-05-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0018_auto_20200530_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodacquired',
            options={'ordering': ['name']},
        ),
    ]
