# Generated by Django 3.1 on 2020-08-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0020_auto_20200807_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemimagethumbnail',
            name='collection_item',
        ),
        migrations.RemoveField(
            model_name='collectionitemimagethumbnail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collectionitemimagethumbnail',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Image Thumbnail'),
        ),
        migrations.DeleteModel(
            name='CollectionItemImage',
        ),
        migrations.DeleteModel(
            name='CollectionItemImageThumbnail',
        ),
    ]
