# Generated by Django 3.1 on 2020-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0021_auto_20200808_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlecap',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bottlecap',
            name='image_thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='Image Thumbnail'),
        ),
    ]
