# Generated by Django 3.1 on 2021-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0022_auto_20200809_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecap',
            name='image_thumbnail_tiny',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_tiny/', verbose_name='Tiny Image Thumbnail'),
        ),
    ]
